name: mdns-example

services:

    mdns:
        image: skhmt/mdns:latest
        restart: unless-stopped
        network_mode: host
        environment:
            IP: 127.0.0.1
            HOST: server1.local, server2.local

    reverse-proxy:
        image: jwilder/nginx-proxy:latest
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            # - ./certs:/etc/nginx/certs:ro    # optional if you need certs for ssh
        networks:
            - proxy_network

    http1:
        image: egladman/redbean
        restart: unless-stopped
        environment:
            VIRTUAL_HOST: server1.local
            VIRTUAL_PORT: 80
        volumes:
            - ./www1:/www
        networks:
            - proxy_network

    http2:
        image: egladman/redbean
        restart: unless-stopped
        environment:
            VIRTUAL_HOST: server2.local
            VIRTUAL_PORT: 80
        volumes:
            - ./www2:/www
        networks:
            - proxy_network

networks:
    proxy_network:
        driver: bridge
